SID = 'ACe9fea1********856190' # You can find SID and AUTH_TOKEN in your Twilio Dashboard 
AUTH_TOKEN = '3777****79c2b' # We can send alerts to our mobile via twilio 
FROM_NUMBER = '+122***106' #recived twilio number
TO_NUMBER = '+91*****0' #your phone number
API_KEY = '058*****a30b4' # Board API
DEVICE_ID = 'BOLT2****' # device id 
MAILGUN_API_KEY = '9003a*****82e52' # specified mailgun api
SANDBOX_URL = 'sandbox24fb16*********2fed.mailgun.org'
SENDER_EMAIL = 'mailgun@sandbox24fb****************.mailgun.org' #mailgun enables us to send alerts to our email
RECIPIENT_EMAIL = 'yasaswiavula@gmail.com'
